[build]
  # Directory to change to before starting a build
  base = "frontend/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "build/"
  
  # Default build command (CI=false disables treating warnings as errors)
  command = "CI=false npm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect all requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy rules (optional - if you want to proxy API calls)
[[redirects]]
  from = "/api/*"
  to = "https://zofaire.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://zofaire.onrender.com/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://zofaire.onrender.com/health"
  status = 200
  force = true